### ISSUE TITLE
NFSW

### ISSUE THREAD

**Issue by irdumbs** [Alzarath/Booru-Cogs#2]
![image](https://cloud.githubusercontent.com/assets/15660809/15951322/9aad5f74-2efa-11e6-80ff-a2aebd3c3a66.png)

**Comment by Alzarath** [comment]
I don't recall 'have a option to disable said content' being a pre-requisite before. I have to assume you're referring to the Dan cog, then. I've been neglecting to add that because Danbooru is terrible, but I'll work at throwing it in there if that's now a requirement.
