### ISSUE TITLE
For Some odd reason the Gel cog isn't working for me

### ISSUE THREAD

**Issue by cygnusgamma** [Alzarath/Booru-Cogs#4]
I had the bot running on a ubuntu server pretty much 24/7 and all the other cogs save for gel work, but for some reason whenever you do any [p]gel command it replies with "Error." Do you know how to fix this issue? I've reinstalled the bot several times and each time it still doesn't want to work. 
![jz2kahd](https://cloud.githubusercontent.com/assets/17586613/19129817/87a2ebe2-8afd-11e6-93a4-5f03e7769b21.png)

**Comment by Alzarath** [comment]
I'm unable to reproduce this issue on my end. Is this still an issue for you? The Gelbooru server may have simply been down.

**Comment by cygnusgamma** [comment]
Yeah it's still a problem, it has been for a month or so. It may just be something on my end that I can't figure out.

**Comment by Alzarath** [comment]
Hop on the [Red - Discord Bot Discord server](https://discord.gg/0k4npTwMvTpv9wrh), shoot me a DM, and we can try to resolve it.
