### ISSUE TITLE
Pony.py and derpibooru filters

### ISSUE THREAD

**Issue by SomewhatDamaged** [Alzarath/Booru-Cogs#5]
The problem being, that the "default" filter is applied to all search requests, limiting the cog to only SFW images, no matter what filters are added/removed.

Can be fixed by having server admins make up a new derpibooru account, set the filter to "everything" and then use the API key in the program with a:

&key=<api key>

Stuck on the end of the URL. I tested this by hardcoding such into a test file, but am not skilled enough with python to implement it with a "ponyset" command.

**Comment by Alzarath** [comment]
Ah, darn. That's something that must have been introduced with the overhaul a few months ago. Sorry for the delay, no idea why I never got an email for this until today. Shouldn't be too hard to fix. I'll get right on it.

**Comment by Alzarath** [comment]
Should be fixed with 046caa1. Please re-open if you're still having issues.
