### ISSUE TITLE
[FR] More info

### ISSUE THREAD

**Issue by ghost** [Alzarath/Booru-Cogs#8]
Well, you could add tags under the image and rating above the image along with author info (maybe) if it's embedded. Would look quite neat.

Thanks.

**Comment by Alzarath** [comment]
I finally got around to finishing this up. See: 48b3979, 66aa78d, 26cb141, f68d032, b30817d, 4b912d3

The author is not something I can get reliably, so I've excluded that. Verbose mode uses embed and supplies the URL to the web page, a small preview image, the rating (and an associated color), and the tags.
