### ISSUE TITLE
Gelbooru search now longer works

### ISSUE THREAD

**Issue by GhostSquad57** [Alzarath/Booru-Cogs#9]
When using the `gelr` command, the full URL isn't returned.
Example:
![2017-02-28_641x146](https://cloud.githubusercontent.com/assets/1379876/23395683/e8aeab4c-fd5d-11e6-9a64-6f07a20bc757.jpg)

**Comment by Alzarath** [comment]
Should be fixed with a712e4a.

**Comment by GhostSquad57** [comment]
Yep. I can confirm this issue has been resolved. Thanks!
